"use client";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./_Components/Header";
import Footer from "./_Components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { cartContext } from "./_context/cartContext";
const inter = Montserrat({ subsets: ["latin"], weight: "700" });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <cartContext.Provider>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </cartContext.Provider>
    </ClerkProvider>
  );
}
