import { Lato } from "next/font/google";
import "./globals.css";
import Header from "./_Components/Header";
import Footer from "./_Components/Footer";

const inter = Lato({ subsets: ["latin"], weight: 700 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
